"""Make logo nullable

Revision ID: adbbc843cbc7
Revises: 
Create Date: 2025-09-20 22:58:20.403837

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbbc843cbc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamecontributorlink')
    op.drop_table('criteria')
    op.drop_table('user')
    op.drop_table('metadataentry')
    op.drop_table('gamejam')
    op.drop_table('jamcomment')
    op.drop_table('gamecomment')
    op.drop_table('downloaditem')
    op.drop_table('jamgamehistorical')
    op.drop_table('screenshot')
    op.drop_table('jamgame')
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('cover', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('logo', sa.VARCHAR(), nullable=False),
    sa.Column('iframe_width', sa.INTEGER(), nullable=False),
    sa.Column('iframe_height', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('short_text', sa.VARCHAR(), nullable=True),
    sa.Column('gif_cover', sa.VARCHAR(), nullable=True),
    sa.Column('cover_color', sa.VARCHAR(), nullable=True),
    sa.Column('platforms', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jamgame',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coolness', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('rating_count', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.Column('question_responses', sa.VARCHAR(), nullable=True),
    sa.Column('gamejam_id', sa.INTEGER(), nullable=True),
    sa.Column('raw_score', sa.FLOAT(), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['gamejam_id'], ['gamejam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenshot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('src', sa.VARCHAR(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jamgamehistorical',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('popularity', sa.INTEGER(), nullable=False),
    sa.Column('coolness', sa.INTEGER(), nullable=False),
    sa.Column('rating_count', sa.INTEGER(), nullable=False),
    sa.Column('fetch_date', sa.DATETIME(), nullable=False),
    sa.Column('jamgame_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['jamgame_id'], ['jamgame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloaditem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('platforms', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('external', sa.BOOLEAN(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamecomment',
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jamcomment',
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_submitted', sa.BOOLEAN(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('jamgame_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['jamgame_id'], ['jamgame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamejam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('logo', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('entries_count', sa.INTEGER(), nullable=True),
    sa.Column('ratings_count', sa.INTEGER(), nullable=True),
    sa.Column('joined_count', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('voting_end_date', sa.DATETIME(), nullable=False),
    sa.Column('hue', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadataentry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criteria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('raw_score', sa.FLOAT(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('jamgame_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['jamgame_id'], ['jamgame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamecontributorlink',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    # ### end Alembic commands ###
